---
# tasks config for haproxy
# Configuration will be split into multiple template files and then concatinated to one big file.
- name: create folder to place cert files
  become: yes
  file:
    path: /etc/haproxy/ssl
    state: directory

- name: create folder to place template files
  become: yes
  file:
    path: /etc/haproxy/templates
    state: directory

- name: Place config for haproxy global
  become: yes
  template:
    src: global.tpl
    dest: /etc/haproxy/templates/000-global.tpl
    backup: yes

- name: Place config for haproxy ssl
  become: yes
  template:
    src: ssl.tpl
    dest: /etc/haproxy/templates/001-ssl.tpl
    backup: yes
  with_items:
  - "{{ crtBase }}"

- name: Place config for haproxy defaults
  become: yes
  template:
    src: defaults.tpl
    dest: /etc/haproxy/templates/002-defaults.tpl
    backup: yes

- name: Place config for haproxy stats
  become: yes
  template:
    src: stats.tpl
    dest: /etc/haproxy/templates/003-stats.tpl
    backup: yes
